name: Test with PM2
on: [push]
jobs:
  Test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install local dependencies
        run: npm install
      
      - name: Run the test and save result
        run: npm run check > test-result.txt
      
      - uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: ./test-result.txt
  
  Deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: actions/download-artifact@v4
        with:
          name: test-output
          path: ./
      
      - name: Display artifact content
        run: cat test-result.txt
      
      # Stopping the container kills all processes inside
      - name: Pull Node Image
        run: docker pull node:22-alpine

      - name: Delete old container
        shell: cmd
        run: docker rm node22PM2 -f || exit /b 0

      - name: Create new container
        run: |
          echo ${{ github.workspace }}
          docker run -d -it --name node22PM2 -p 3001:3000 -v ${{ github.workspace }}:/node-app -w /node-app --entrypoint sh node:22-alpine

      - name: Test Node Setup
        shell: cmd
        run: |
          docker exec -i node22PM2 node -v
          docker exec -i node22PM2 npm -v
      
      - name: Install packages
        run: docker exec -i node22PM2 npm install

      - name: Install pm2
        run:  | 
          docker exec -i node22PM2 npm install pm2 -g
          docker exec -i node22PM2 pm2 update
      
      - name: Cleanup
        shell: cmd
        run: docker exec -i node22PM2 pm2 delete node-app || exit /b 0
      
      - name: Start Application
        run: docker exec -i node22PM2 pm2 start "./src/server.js" --name node-app
      
      - name: Persist pm2 configuration
        run: |
          docker exec -i node22PM2 pm2 save

      - name: Final Test
        shell: cmd
        run: |
          curl http://localhost:3001
          curl http://localhost:3001
