name: Test with Docker
on: [push]
jobs:
  Test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install local dependencies
        run: npm install
      
      - name: Run the test and save result
        run: npm run check > test-result.txt
      
      - uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: ./test-result.txt
  
  Deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: actions/download-artifact@v4
        with:
          name: test-output
          path: ./
      
      - name: Display artifact content
        run: cat test-result.txt
      
      # Stopping the container kills all processes inside
      - name: Pull Node Image
        run: docker pull node:22-alpine

      - name: Check if container exists
        id: check-container
        run: |
          $containerExists = if (docker ps -a | Select-String "node22") { "true" } else { "false" }
          echo "container_exists=$containerExists" >> $env:GITHUB_OUTPUT

      - name: Restart existing container
        if: steps.check-container.outputs.container_exists == 'true'
        run: |
          docker stop node22
          docker start node22

      - name: Create new container
        if: steps.check-container.outputs.container_exists != 'true'
        run: |
          echo ${{ github.workspace }}
          docker run -d -it --name node22 -p 3000:3000 -v ${{ github.workspace }}:/node-app -w /node-app --entrypoint sh node:22-alpine

      - name: Test Node Setup
        shell: cmd
        run: |
          docker exec -i node22 node -v
          docker exec -i node22 npm -v
      
      - name: Install packages
        run: docker exec -i node22 npm install
      
      - name: Start the server # Stop Using: docker stop node22
        shell: cmd
        run: start /b docker exec -i node22 npm start

      - name: Final Test
        shell: cmd
        run: |
          curl http://localhost:3000
          curl http://localhost:3000
